# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Smart GroundHog
header-img: img/home-bg.jpg
email: jqian1996@gmail.com
baseurl: "/SmartGroungHog" # the subpath of your site, e.g. /blog
#url: "http://smartgroundhog.cn" # the base hostname & protocol for your site
github_username:  JieQ1996
#theme: jekyll-theme-architect


# Build settings
markdown: kramdown
